#!/usr/bin/env bash
# Installs and patches Godot's Android build template.
#
# android/build/ is gitignored (1.2 GB of engine source) and is regenerated by
# "Install Android Build Template", so every patch it needs has to live here
# rather than in the tree. Run before any Android export on a fresh checkout.
set -euo pipefail

TPL="${GODOT_TEMPLATES:-$HOME/Library/Application Support/Godot/export_templates/4.3.stable}"
SRC="$TPL/android_source.zip"
[ -f "$SRC" ] || { echo "!! no android_source.zip at $TPL"; exit 1; }

if [ ! -d android/build ]; then
  mkdir -p android/build
  unzip -q -o "$SRC" -d android/build
  touch android/.gdignore
  # Godot looks for this at android/.build_version, NOT inside build/.
  printf '4.3.stable' > android/.build_version
  echo "installed android build template"
fi

# Play requires targetSdk 35 for new apps, and AGP requires compileSdk >= targetSdk.
# Godot 4.3's template ships 34 with no property to override compileSdk, so it is
# patched here. NOTE: this buys time, it is not the durable fix — Google raises the
# floor every August, and API 36 needs a newer AGP than Godot 4.3 ships. The real
# answer is a Godot 4.5+ upgrade.
sed -i '' 's/compileSdk *: *34,/compileSdk         : 35,/' android/build/config.gradle
sed -i '' 's/targetSdk *: *34,/targetSdk          : 35,/' android/build/config.gradle
grep -q 'suppressUnsupportedCompileSdk' android/build/gradle.properties 2>/dev/null || \
  echo 'android.suppressUnsupportedCompileSdk=35' >> android/build/gradle.properties

grep -E 'compileSdk|targetSdk' android/build/config.gradle | head -2
